spring:
  datasource:
    url: jdbc:postgresql://ep-twilight-wildflower-49771409.ap-southeast-1.aws.neon.tech/neondb
    username: chan00012
    password: password=APEkWatq95jm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

send-grid:
  api-key: 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