name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Access ./gradlew file
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: invitation-backend-031524
          heroku_email: cstrobles@gmail.com
        env:
          HD_DATASOURCE_URL: ${{secrets.DATASOURCE_URL}}
          HD_DATASOURCE_USERNAME: ${{secrets.DATASOURCE_USERNAME}}
          HD_DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
          HD_SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}