name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: 709d593d-1b49-4d6d-b06c-9139f84fa1ad
          heroku_app_name: invitation-backend-031524
          heroku_email: cstrobles@gmail.com
